### ISSUE TITLE
send batch email with dynamic content

### ISSUE THREAD

**Issue by raheemrize** [maurymmarques/postmark-cakephp#11]
I had a strange problem with email sending through cakephp and postmark.

I have installed postmark-cakephp library in my cakephp application. I'm able to send email to single user and able to send email to multiple users with same email content (message) but here my requirement is I need to send email to multiple users with some dynamic email content. (contains user id)

I'm able to do this in a for loop but I want to send batch emails with dynamic content with a single call.

It is possible in official php postmark library https://github.com/wildbit/postmark-php/wiki/Sending-Batches 

But how to make it with this library ?

**Comment by maurymmarques** [comment]
Hi raheemrize,

I'm sorry for taking so long to asnwer your question.
When I developed this plugin I had not thought about sending emails in batches.
At the time I'm not working with PHP, but you can try to develop that feature, I'd gladly merge a new feature.
I can try to help you if you need some help.
I think the messages should just be an array like the example that you sent me (https://github.com/wildbit/postmark-php/wiki/Sending-Batches).

Do you use Skype or something else?

Feel free to contact me.

**Comment by maurymmarques** [comment]
Hi, raheemrize

Did you try or are you trying something?
